export {default as Header} from './Header'
export {default as LandingPage} from './LandingPage'
export {default as Auth} from './Auth'
export {default as ForgetPassword} from './ForgetPassword'
export {default as ResetPassword} from './ResetPassword'
export {default as Profile} from './Profile'